/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/scene.gltf
Author: LePoint_BAT (https://sketchfab.com/LePointBAT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-japan-mazda-mx5-miata-60d1e139e73e4f00bdaebf394cc0f6ad
Title: TOON Japan : Mazda MX5 Miata
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.23, 0]}>
        <group position={[-0.31, -0.12, -0.52]}>
          <mesh geometry={nodes.Object_14.geometry} material={materials.Black} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Caliper} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Disk} />
        </group>
        <group position={[0.31, -0.12, -0.52]}>
          <mesh geometry={nodes.Object_19.geometry} material={materials.Black} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Caliper} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.Disk} />
        </group>
        <group position={[0, -0.01, -0.69]} rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
          <mesh geometry={nodes.Object_24.geometry} material={materials.White_Lights} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.Black} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.Paint} />
        </group>
        <group position={[0.01, -0.13, 0.38]}>
          <mesh geometry={nodes.Object_29.geometry} material={materials.Black} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Caliper} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.Rims} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.Disk} />
        </group>
        <mesh geometry={nodes.Object_4.geometry} material={materials.White_Lights} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Red_Lights} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Paint} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Caliper} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Licence_Plate} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Interior} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Windows} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/scene.gltf')
